node:
    image: sorcerer01/statescore
    links:
        - redis
    ports:
        - "80:80"
    environment:
        - HOST_HOSTNAME=development
        - REDISHOST=redis

redis:
    image: redis
    ports:
        - "6379:6379"
