# yml file used in Docker-Compose to deploy statescore in a multi container on multi host deployment
#forked from https://docs.clusterhq.com/en/1.14.0/_downloads/flocker-swarm-tutorial-node1.yml

#version 2 necessary for overlay networking
version: "2"
#volume definition
volumes:
   redis:
      driver: "flocker"
      driver_opts:
        size: "10GiB"
        profile: "bronze"
#services definition
#overlay networkin enabled
services:
   statescore:
     image: sorcerer01/statescore
     ports:
        -  "80:80"
     environment:
#constraining the flocker node
        - "constraint:flocker-node==1"
        - "HOST_HOSTNAME=flocker_node_1"
        - "REDISHOST=redis"
     network_mode: "bridge"
     links:
        - "redis:redis"
   redis:
     image: redis
     ports:
        -  "6379:6379"
     environment:
#constraining the flocker node
        - "constraint:flocker-node==2"
     network_mode: "bridge"
     volumes:
        - 'redis:/data'
