apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1statescore
  labels:
    app: statesco
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: statescore2
  labels:
    name: statescore
spec:
  containers:
    - resources:
      image: sorcerer01/statescore
      name: statescore
      env:
        - name: HOST_HOSTNAME
          value: kube1
      ports:
        - containerPort: 80
          name: node
      volumeMounts:
        - name: local-statescore
          mountPath: /opt/userlist/
          readOnly: false
  volumes:
    - name: local-statescore
        persistentVolumeClaim:
          claimName: claim1statescore
