apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-statescore
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/local-statescore/
