apiVersion: v1
kind: Service
metadata:
  labels:
    name: statescore
    type: runningapplication
  name: statescore
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    name: statescore
