apiVersion: v1
kind: Pod
metadata:
  name: statescore
  labels:
    name: statescore
spec:
  containers:
    - resources:
      image: sorcerer01/statescore
      name: statescore
      env:
        - name: HOST_HOSTNAME
          value: kube1
      ports:
        - containerPort: 80
          name: node
      volumeMounts:
        - name: local-statescore
          mountPath: /opt/userlist/
          readOnly: false
  volumes:
    -  hostPath:
         path: /tmp
       name: local-statescore
